### ISSUE TITLE
OSX installation issue

### ISSUE THREAD

**Issue by ChristianLinenko** [joeferraro/MavensMate-Atom#128]
After installing the plugin in Atom and configuring the MM plugin, I go to create a new project and it looks like this:

![screenshot 2014-12-30 07 32 44](https://cloud.githubusercontent.com/assets/6098777/5618835/6ed50f38-94d1-11e4-8eac-8bf3a5ad5d8f.png)

I can't create a project, rendering this plugin unusable for me. Any help getting this fixed would be awesome.

Thanks guys. Great work so far!

**Comment by joeferraro** [comment]
Hi @ChristianLinenko, thanks for the information. I assume you mean "Mac OSX"? Is there anything in the Atom console?

**Comment by ChristianLinenko** [comment]
Hey @joeferraro. Any updates on this? Thanks so much for your time.

**Comment by ChristianLinenko** [comment]
@joeferraro When I try to reinstall MavensMate on Atom, I'm getting this error. Any ideas?

Installing “MavensMate-Atom@0.0.14” failed.

npm http GET https://registry.npmjs.org/body-parser/1.5.2
npm http GET https://registry.npmjs.org/cloneextend/0.0.3
npm http GET https://registry.npmjs.org/color/0.7.1
npm ERR! git fetch -a origin (git://github.com/atom-community/autocomplete-plus) fatal: unable to connect to github.com:
npm ERR! git fetch -a origin (git://github.com/atom-community/autocomplete-plus) github.com[0: 192.30.252.128]: errno=Connection refused
npm http GET https://registry.npmjs.org/daemon
npm http GET https://registry.npmjs.org/emissary/1.2.1
npm http GET https://registry.npmjs.org/firebase/1.0.21
npm http GET https://registry.npmjs.org/fuzzaldrin
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/jquery/2.1.0
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/loophole/1.0.0
npm http GET https://registry.npmjs.org/mavensmate/0.0.28
npm http GET https://registry.npmjs.org/node-uuid/1.4.1
npm http GET https://registry.npmjs.org/moment/2.8.3
npm http GET https://registry.npmjs.org/open/0.0.5
npm http GET https://registry.npmjs.org/pluralize/1.0.1
npm http GET https://registry.npmjs.org/portfinder
npm http GET https://registry.npmjs.org/semver/3.0.1
npm http GET https://registry.npmjs.org/repeat/0.0.6
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/serve-index
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/tmp/0.0.24
npm http GET https://registry.npmjs.org/typechecker/2.0.8
npm http GET https://registry.npmjs.org/watchjs
npm http GET https://registry.npmjs.org/unzip
npm http GET https://registry.npmjs.org/watchr/2.4.11
npm http GET https://registry.npmjs.org/ansi-to-html
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/underscore-plus
npm ERR! Error: Command failed: fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Socket.<anonymous> (child_process.js:979:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/christianl/.atom/.apmrc" "install" "/Users/christianl/.atom/.node-gyp/.atom/.apm/MavensMate-Atom/0.0.14/package.tgz" "--target=0.20.0" "--arch=x64"
npm ERR! cwd /private/var/folders/bq/mlqdxq_90_vcp7dp9fjrt6c5fykfxq/T/apm-install-dir-115013-29636-19i4xqy
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm http 304 https://registry.npmjs.org/emissary/1.2.1
npm http 304 https://registry.npmjs.org/body-parser/1.5.2
npm http 304 https://registry.npmjs.org/daemon
npm http 304 https://registry.npmjs.org/cloneextend/0.0.3
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/firebase/1.0.21
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/fuzzaldrin
npm http 304 https://registry.npmjs.org/color/0.7.1
npm http 304 https://registry.npmjs.org/jquery/2.1.0
npm http 304 https://registry.npmjs.org/lodash/2.4.1
npm http 304 https://registry.npmjs.org/mavensmate/0.0.28
npm http 304 https://registry.npmjs.org/loophole/1.0.0
npm http 304 https://registry.npmjs.org/moment/2.8.3
npm http 304 https://registry.npmjs.org/pluralize/1.0.1
npm http 304 https://registry.npmjs.org/portfinder
npm http 304 https://registry.npmjs.org/semver/3.0.1
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/node-uuid/1.4.1
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/repeat/0.0.6
npm http 304 https://registry.npmjs.org/serve-index
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/tmp/0.0.24
npm http 304 https://registry.npmjs.org/open/0.0.5
npm http 304 https://registry.npmjs.org/typechecker/2.0.8
npm http 304 https://registry.npmjs.org/ansi-to-html
npm http 304 https://registry.npmjs.org/unzip
npm http 304 https://registry.npmjs.org/watchjs
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/watchr/2.4.11
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/bq/mlqdxq_90_vcp7dp9fjrt6c5fykfxq/T/apm-install-dir-115013-29636-19i4xqy/npm-debug.log
npm ERR! not ok code 0

**Comment by ChristianLinenko** [comment]
Found this in the console when I opened Atom today.

Could not activate MavensMate project. MavensMate will not function correctly.
Could not initiate existing Project instance: 
Error: Could not log in to Salesforce.com: 
Error: certificate not trusted

Thoughts?

**Comment by joeferraro** [comment]
Hi @ChristianLinenko, this is a duplicate of https://github.com/joeferraro/MavensMate-Atom/issues/129

**Comment by joeferraro** [comment]
FYI, I've pushed v0.0.15 of the package which resolves several issues and starts the long arduous process of updating deprecated atom references: https://atom.io/packages/mavensmate-atom

**Comment by ChristianLinenko** [comment]
@joeferraro Hey bud. Still having the same issue above. I'm unable to create a project.

**Comment by joeferraro** [comment]
Hi @ChristianLinenko your issue is evidence of a problem actually installing MavensMate, versus an issue creating a project. When you install/reinstall, are you doing so via Atom or the command line? If via Atom, can you try uninstalling then reinstalling via the command line: `apm install MavensMate-Atom` (you may need to `sudo`)?

**Comment by ChristianLinenko** [comment]
I tried that and got the same result when trying to create a new project.

Command Line:
Mac-Attack:Code christianl$ apm install MavensMate-Atom
Installing MavensMate-Atom to /Users/christianl/.atom/packages ✓
Mac-Attack:Code christianl$ 

What am I missing dude?

**Comment by joeferraro** [comment]
@ChristianLinenko the error message states additional logs can be found at:

```
npm ERR!     /private/var/folders/bq/mlqdxq_90_vcp7dp9fjrt6c5fykfxq/T/apm-install-dir-115013-29636-19i4xqy/npm-debug.log
```

can you paste the contents of that file?

**Comment by ChristianLinenko** [comment]
That file doesn't exist in that directory.

/private/var/folders/bq/mlqdxq_90_vcp7dp9fjrt6c5fykfxq/T/apm-install-dir-1141129-10825-nnwxfc.

![screenshot 2015-02-02 14 12 23](https://cloud.githubusercontent.com/assets/6098777/6010239/9ab690e8-aae5-11e4-98f0-772345a17eff.png)

**Comment by joeferraro** [comment]
OK, well if you can generate that error again, it'd be helpful if you could post the contents of the log file it generates. At this point, I don't have a clue what your issue may be. The more info you can provide, the better.

**Comment by ChristianLinenko** [comment]
It's not erroring on install. The contents of the package are below. Just change the file extension to .zip. Let me know if you find anything.

![image](https://cloud.githubusercontent.com/assets/6098777/6010367/843b4970-aae6-11e4-9523-6d675a75412c.png)

**Comment by joeferraro** [comment]
@ChristianLinenko that file is not working for me and unfortunately, I'm unable to reproduce this on either of my OSX machines. For now, I'm labeling at more-information-needed.

**Comment by seanhharrison** [comment]
@ChristianLinenko I tried opening this file and also was unable. Love the Hall Monitor avatar, btw

Just to take a step back, which version of Atom & OSX you have there and which version of MM does Atom say is installed?  

If still MM 0.14, can you click the Uninstall button and have the process run successfully?

**Comment by joeferraro** [comment]
Closing until more information is provided
