### ISSUE TITLE
Uncaught TypeError: document.querySelector(...).appendLeft is not a function

### ISSUE THREAD

**Issue by jdr0dn3y** [joeferraro/MavensMate-Atom#290]
[Enter steps to reproduce below:]
I got this error on just starting up Atom.

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v1.0.6

### Stack Trace

Uncaught TypeError: document.querySelector(...).appendLeft is not a function

```
At /Users/justin/.atom/packages/MavensMate-Atom/lib/status-bar-view.coffee:60

TypeError: document.querySelector(...).appendLeft is not a function
    at StatusBarView.module.exports.StatusBarView.attach (/Users/justin/.atom/packages/MavensMate-Atom/lib/status-bar-view.coffee:60:53)
    at StatusBarView.module.exports.StatusBarView.initialize (/Users/justin/.atom/packages/MavensMate-Atom/lib/status-bar-view.coffee:43:12)
    at StatusBarView.View [as constructor] (/opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new StatusBarView (/Users/justin/.atom/packages/MavensMate-Atom/lib/status-bar-view.coffee:22:43)
    at /Users/justin/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:98:43
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "followSymlinks": false,
    "projectHome": "/Users/justin/source"
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v1.0.6
color-picker, v2.0.13
file-icons, v1.6.11
fonts, v1.0.0
github-notifications, v0.1.1
github-utils, v0.7.0
language-mongodb, v0.2.0
minimap, v4.16.0
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by alker7** [comment]
same here.

**Comment by rwparris2** [comment]
Same, Atom 1.2 on Windows 7.

**Comment by thvd** [comment]
I think it has to do something with the new Atom 1.2 version. Before it didn't exist as far as I know. 
I've the same issue on Ubuntu 15.10.

**Comment by jeancdc** [comment]
Same problem.

I use:
- Atom 1.2.0
- MavensMate-Atom 1.0.6
- Mac OSX 10.11.1

**Comment by thesandbender** [comment]
It looks like MM is using jQuery to access the status bar.  This was deprecated and actually completely dropped a few weeks ago with this checkin:

https://github.com/atom/status-bar/commit/b37cc091a481eca63b72447be0ca23fd56573d7c

The status-bar page has the new/current api:

https://github.com/atom/status-bar

**Comment by agentgill** [comment]
Same issue. Any workaround?

**Comment by sfukumaru** [comment]
Also same issue... Does anyone resolve this with any workaround???

**Comment by CinnaCube** [comment]
Same issue
windows 7
Atom 1.2.1
Mavensmate 1.0.6

**Comment by celador** [comment]
Same issue.  Plugin doesn't startup either, so I can't save my files.

**Comment by schnism** [comment]
Confirmed, same here after updating to Atom 1.2

**Comment by joeyguacamole** [comment]
Temporary workaround:
Go to package directory (e.g. `~/.atom/packages/MavensMate-Atom` on Mac) and edit the file `lib/status-bar-view.coffee`

Replace line 57
```coffee
document.querySelector('status-bar').appendLeft(this)
```
with
```coffee
document.querySelector('status-bar').addLeftTile({item: this, priority: 0})
```

**Comment by joeferraro** [comment]
@joeyguacamole PR?

**Comment by joeferraro** [comment]
thanks @joeyguacamole fixed in 1.0.7

**Comment by zainabShikari** [comment]
I tried to update it to 1.0.7 and still shows the same error..
